### ISSUE TITLE
How to import an XML parser in a gradle task for an Android library module

### ISSUE THREAD

**Issue by sahibjaspal** [gradle-guides/writing-gradle-tasks#15]
I get this compile time error when I try to XmlPullParser

`Caused by: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
script '/Users/sahibjaspal/Documents/trailmix-android/lib/generatetypography.gradle': 2: unable to resolve class org.xmlpull.v1.XmlPullParserFactory
 @ line 2, column 1.
   import org.xmlpull.v1.XmlPullParserFactory
   ^

script '/Users/sahibjaspal/Documents/trailmix-android/lib/generatetypography.gradle': 1: unable to resolve class org.xmlpull.v1.XmlPullParser
 @ line 1, column 1.
   import org.xmlpull.v1.XmlPullParser
   ^

2 errors

    at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:311)
    at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:991)
    at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:651)
    at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:600)
    at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:390)
    at groovy.lang.GroovyClassLoader.access$300(GroovyClassLoader.java:89)
    at groovy.lang.GroovyClassLoader$5.provide(GroovyClassLoader.java:330)
    at groovy.lang.GroovyClassLoader$5.provide(GroovyClassLoader.java:327)
    at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:147)
    at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:325)
    at org.gradle.groovy.scripts.internal.DefaultScriptCompilationHandler.compileScript(DefaultScriptCompilationHandler.java:133)
    ... 185 more
Cause 2: java.lang.IllegalStateException: compileSdkVersion is not specified.
    at com.google.common.base.Preconditions.checkState(Preconditions.java:507)
    at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:693)
    at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:81)
    at com.android.build.gradle.BasePlugin.lambda$createTasks$4(BasePlugin.java:651)
    at com.android.build.gradle.internal.crash.CrashReporting$afterEvaluate$1.execute(crash_reporting.kt:37)
    at com.android.build.gradle.internal.crash.CrashReporting$afterEvaluate$1.execute(crash_reporting.kt)`

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #272](https://github.com/gradle/guides/issues/272) via [**ZenHub**](https://www.zenhub.com/)
